name: flutter_busylib
description: BusyWin ERP Web Service Package
version: 0.0.1
homepage: 'https://github.com/devstroop/flutter_busylib'

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
